const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Behaviors.scrollto,
		C3.Behaviors.Pin,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.TiledBg.Acts.Destroy
	];
};
self.C3_JsPropNameTable = [
	{Teclado: 0},
	{bachground: 0},
	{Sólido: 0},
	{plataforma: 0},
	{Plataforma: 0},
	{RestritoAoLayout: 0},
	{CentrarEm: 0},
	{jogador: 0},
	{Fixar: 0},
	{animação: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Senóide: 0},
	{moeda: 0},
	{Âncora: 0},
	{moedas: 0},
	{Ação: 0},
	{"1inimigo": 0},
	{marcador: 0},
	{espinho: 0},
	{fimDeFase: 0},
	{Áudio: 0},
	{Sprite: 0},
	{plate2: 0},
	{"2animação": 0},
	{"2jogador": 0},
	{PlanoDeFundoEmBlocos2: 0},
	{plata: 0},
	{M2: 0},
	{moedinha: 0},
	{espinho2: 0},
	{fim: 0},
	{fim1: 0},
	{fundoinicio: 0},
	{chãoa: 0},
	{figurante1: 0},
	{algumacoisa: 0},
	{espinhodenovo: 0},
	{persona1: 0},
	{Sprite3: 0},
	{botãoinicio: 0},
	{Mouse: 0},
	{botaocontinuar: 0},
	{nome: 0},
	{telafimdejogo: 0},
	{textoparabens: 0},
	{Textoparabens2: 0},
	{botãovoltar: 0},
	{pontos: 0},
	{Moedas: 0}
];

self.InstanceType = {
	Teclado: class extends self.IInstance {},
	bachground: class extends self.ITiledBackgroundInstance {},
	plataforma: class extends self.ITiledBackgroundInstance {},
	jogador: class extends self.ISpriteInstance {},
	animação: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	moeda: class extends self.ISpriteInstance {},
	moedas: class extends self.ITextInstance {},
	_1inimigo: class extends self.ISpriteInstance {},
	marcador: class extends self.ISpriteInstance {},
	espinho: class extends self.ISpriteInstance {},
	fimDeFase: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	plate2: class extends self.ISpriteInstance {},
	_2animação: class extends self.ISpriteInstance {},
	_2jogador: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	plata: class extends self.ITiledBackgroundInstance {},
	M2: class extends self.ITextInstance {},
	moedinha: class extends self.ISpriteInstance {},
	espinho2: class extends self.ISpriteInstance {},
	fim: class extends self.ISpriteInstance {},
	fim1: class extends self.ISpriteInstance {},
	fundoinicio: class extends self.ISpriteInstance {},
	chãoa: class extends self.ISpriteInstance {},
	figurante1: class extends self.ISpriteInstance {},
	algumacoisa: class extends self.ISpriteInstance {},
	espinhodenovo: class extends self.ISpriteInstance {},
	persona1: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	botãoinicio: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	botaocontinuar: class extends self.ISpriteInstance {},
	nome: class extends self.ITextInstance {},
	telafimdejogo: class extends self.ISpriteInstance {},
	textoparabens: class extends self.ITextInstance {},
	Textoparabens2: class extends self.ITextInstance {},
	botãovoltar: class extends self.ISpriteInstance {}
}